### PR TITLE
Heroku prep

### PR DESCRIPTION
**Pull request by hassanshamim**
some old stuff, but mostly bump to django 2.0 and making it heroku compatible.

### CODE REVIEW

**Comment by hassanshamim** [comment]
closes #5 #6 and #7

**Comment by hassanshamim** [comment]
next time i squash 😢

**Comment by amna** [comment]
You squash what?

Amna Shamim
Writer
Website Email
Featured in: Glamour Magazine, Entrepreneur, Business Insider, HuffPost, Bust, Paste

**Comment by hassanshamim** [comment]
Basically this.
Just keeps the history a bit cleaner.
squash on merge

**Comment by amna** [comment]
Ah. That makes perfect sense. Thank you.

**Pull request merged**
